[package]
name = "keyboard-types"
version = "0.6.2"
authors = ["Pyfisch <pyfisch@posteo.org>"]
description = "Contains types to define keyboard related events."
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pyfisch/keyboard-types"
keywords = ["keyboard", "input", "event", "webdriver"]

[features]
default = ["serde", "webdriver"]
webdriver = ["unicode-segmentation"]

[dependencies]
bitflags = "1.0.0"
serde = { version = "1.0.0", optional = true, features = ["derive"] }
unicode-segmentation = { version = "1.2.0", optional = true }

[badges]
travis-ci = { repository = "pyfisch/keyboard-types" }
